[pytest]
filterwarnings =
    ignore::DeprecationWarning
    # huggingface_hub warns that Windows can't create symlinks in its cache; an environment property
    ignore:.*huggingface_hub. cache-system uses symlinks.*:UserWarning
    ignore:.*torch.jit.trace.*:FutureWarning
    ignore:Converting a tensor to a Python boolean:torch.jit.TracerWarning
