[project]
name = "n-queens-solver-with-bitmask-optimization"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "manim>=0.21.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "nqueens_solver"
