[project]
name = "offline-dictionary-thesaurus-with-fuzzy-lookup"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "rapidfuzz>=3.14.6",
    "rich>=15.0.0",
    "typer>=0.27.2",
    "wn>=1.1.1",
]

[project.scripts]
offline-dict = "offline_dictionary.cli:app"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "offline_dictionary"
