"""``readme-gen``: draft or refresh a README from what is actually in the repository."""

import os
import tempfile
from pathlib import Path
from typing import Annotated

import typer

from readme_generator.document import has_blocks, merge_document, render_document
from readme_generator.generate import generate_sections

app = typer.Typer(add_completion=False, help=__doc__)


def write_atomic(path: Path, text: str) -> None:
    """Write via a temp file in the same directory, so a crash never leaves half a README."""
    fd, temp = tempfile.mkstemp(dir=path.parent, prefix=".readme-gen-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
        os.replace(temp, path)
    except BaseException:
        Path(temp).unlink(missing_ok=True)
        raise


def _fail(message: str, code: int = 2) -> typer.Exit:
    typer.echo(message, err=True)
    return typer.Exit(code)


@app.command()
def main(
    path: Annotated[Path, typer.Argument(help="Repository root to describe.")] = Path(
        "."
    ),
    output: Annotated[
        Path | None,
        typer.Option(
            "--output", "-o", help="README to write (default: PATH/README.md)."
        ),
    ] = None,
    stdout: Annotated[
        bool,
        typer.Option(
            "--stdout", help="Print the generated README instead of writing it."
        ),
    ] = False,
    check: Annotated[
        bool,
        typer.Option(
            "--check",
            help="Write nothing; exit 1 if the README is missing or out of date.",
        ),
    ] = False,
    force: Annotated[
        bool,
        typer.Option(
            "--force", help="Overwrite an existing README that has no generated blocks."
        ),
    ] = False,
    depth: Annotated[
        int,
        typer.Option(
            "--depth", min=1, max=6, help="Directory levels shown in the project tree."
        ),
    ] = 2,
) -> None:
    """Generate PATH/README.md, or refresh only its ``readme-gen`` blocks when it already has them."""
    if not path.is_dir():
        raise _fail(f"{path} is not a directory")
    target = output if output is not None else path / "README.md"
    generated = generate_sections(path, target, depth)
    for warning in generated.warnings:
        typer.echo(f"warning: {warning}", err=True)
    fresh = render_document(generated.sections)

    if stdout:
        typer.echo(fresh, nl=False)
        return

    if not target.exists():
        if check:
            raise _fail(f"{target} is missing", 1)
        write_atomic(target, fresh)
        typer.echo(f"Wrote {target} ({len(generated.sections)} sections)")
        return

    existing = target.read_text(encoding="utf-8")
    if not has_blocks(existing):
        if check:
            raise _fail(
                f"{target} was not generated by readme-gen, so it cannot be checked", 1
            )
        if not force:
            raise _fail(
                f"{target} already exists and has no readme-gen blocks. Re-run with --force to replace it, "
                "--stdout to preview, or -o to write elsewhere."
            )
        write_atomic(target, fresh)
        typer.echo(f"Replaced {target} ({len(generated.sections)} sections)")
        return

    merged, report = merge_document(existing, generated.sections)
    changes = {
        "updated": report.updated,
        "added": report.added,
        "removed": report.removed,
    }
    summary = "; ".join(
        f"{verb} {', '.join(ids)}" for verb, ids in changes.items() if ids
    )
    if merged == existing:
        typer.echo(f"{target} is up to date")
        return
    if check:
        raise _fail(f"{target} is out of date ({summary})", 1)
    write_atomic(target, merged)
    typer.echo(f"Refreshed {target}: {summary}")
